name: Terraform Dev Deployment

on:
  push:
    branches:
      - dev
  workflow_dispatch:   

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    defaults:
      run:
        shell: bash
        working-directory: ./envs/dev   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5   

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: ./dev/tfplan

  manual_approval:
    name: Wait for Approval
    needs: terraform
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://console.aws.amazon.com   
    steps:
      - name: Approval Step
        run: echo "Waiting for approval before apply"

  terraform_apply:
    name: Terraform Apply
    needs: manual_approval
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./envs/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tf-plan
          path: ./envs/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
